// frontend/src/components/common/nm-column.tsx
import { IColumn } from '@/types';

export default {
  name: 'NmColumn',
  props: {
    renderHeader: {
      type: Function,
    },
    showOverflowTooltip: {
      type: Boolean,
      default: true,
    },
  },
  data() {
    return {};
  },
  methods: {
    defaultRender(h: CreateElement, { column }: IColumn) {
      console.log(column);
      return <div v-bk-overflow-tips>{ column.label }</div>;
    },
  },
  render() {
    console.log(this.$attrs, this.props);
    return <bk-table-column
      show-overflow-tooltip={ this.showOverflowTooltip }
      renderHeader={ this.renderHeader || this.defaultRender}
      attrs={this.$attrs}
      scopedSlots={{
        default: proxy => this.$scopedSlots.default(proxy),
      }} />;
  },
};

// frontend/src/components/common/nm-column.vue
<template>
  <bk-table-column
    :prop="prop"
    :show-overflow-tooltip="showOverflowTooltip"
    :render-header="renderHeader || defaultRender"
    v-bind="$attrs"
    v-on="$listeners">
    <template #default="{ row }">
      <slot :row="row">{{ prop ? row[prop] : null }}</slot>
    </template>
  </bk-table-column>
</template>

<script>
export default {
  name: 'NmColumn',
  props: {
    prop: {
      type: String,
      default: '',
    },
    renderHeader: {
      type: Function,
    },
    showOverflowTooltip: {
      type: Boolean,
      default: true,
    },
  },
  data() {
    return {};
  },
  methods: {
    defaultRender(h, { column }) {
      return h('div', {
        class: 'text-ellipsis',
        directives: [
          { name: 'bk-overflow-tips' },
        ],
      }, column.label);
    },
  },
};
</script>
